emp:
  info:
    company:
      location: Channai
      name: Mphasis
      size: 300
      type: IT
    empName: Teja
    empNo: 3044
    favColors:
    - Black
    - Blue
    - Orange
    idDetails:
      PANID: 764HFUPK4081
      aadharNo: 875643565478
      voterID: 65748865
    nickNames:
    - Nani
    - puppy
    - Chottu
    phoneNumbers:
    - 9999999999
    - 8888888888
    - 7777777777
    - 6666666666
    - 6666666666
